
global_split_ratio: 0.5

nl_60m:
  houses_ind: 30
  total_pairs_ind: 3900
  num_agg: 3
  num_houses_agg: 22 # 22
  total_pairs_agg: 150

ge_60m:
  houses_ind: 6
  total_pairs_ind: 300
  num_agg: 1
  num_houses_agg: 3
  total_pairs_agg: 50

ge_30m:
  houses_ind: 6
  total_pairs_ind: 300
  num_agg: 1
  num_houses_agg: 3
  total_pairs_agg: 50

ge_15m:
  houses_ind: 6
  total_pairs_ind: 300 # 240
  num_agg: 1
  num_houses_agg: 3
  total_pairs_agg: 50 # 240

uk_30m:
  total_pairs_ind: 1800
  num_houses_agg: 10
  total_pairs_agg: 600
  num_agg: -1 # unused

uk_60m:
  total_pairs_ind: 1800
  num_houses_agg: 10
  total_pairs_agg: 600
  num_agg: -1 # unused


